// ReSharper disable InconsistentNaming
namespace EyeAuras.Memory.KD.Internal;

internal static class DBKIoctlCodes
{
    public const int currentversion = 2000027;

    public const uint FILE_ANY_ACCESS = 0;
    public const uint FILE_SPECIAL_ACCESS = FILE_ANY_ACCESS;
    public const uint FILE_READ_ACCESS = 0x0001;
    public const uint FILE_WRITE_ACCESS = 0x0002;
    public const uint FILE_RW_ACCESS = FILE_READ_ACCESS | FILE_WRITE_ACCESS;

    public const uint METHOD_BUFFERED = 0;
    public const uint METHOD_IN_DIRECT = 1;
    public const uint METHOD_OUT_DIRECT = 2;
    public const uint METHOD_NEITHER = 3;
    public const uint FILE_DEVICE_UNKNOWN = 0x00000022;
    public const uint FILE_DEVICE_BLACKBONE = 0x8005;
    public const uint IOCTL_UNKNOWN_BASE = FILE_DEVICE_UNKNOWN;

    private static uint CTL_CODE(uint deviceType, uint function, uint method, uint access)
    {
        return (deviceType << 16) | (access << 14) | (function << 2) | method;
    }

    public static readonly uint IOCTL_CE_READMEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0800, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_WRITEMEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0801, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_OPENPROCESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0802, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_QUERY_VIRTUAL_MEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0803, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_TEST = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0804, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETPEPROCESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0805, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_READPHYSICALMEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0806, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_WRITEPHYSICALMEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0807, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETPHYSICALADDRESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0808, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETCR3 = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x080A, METHOD_BUFFERED, FILE_RW_ACCESS);
    
    /// <summary>Marked as obsolete, returns 0</summary>
    public static readonly uint IOCTL_CE_GETSDT = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x080C, METHOD_BUFFERED, FILE_RW_ACCESS);
    
    public static readonly uint IOCTL_CE_INITIALIZE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x080D, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETIDT = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x080F, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_HOOKINTS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0810, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_DEBUGPROCESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0811, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_RETRIEVEDEBUGDATA = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0812, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_STARTPROCESSWATCH = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0813, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETPROCESSEVENTS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0814, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETTHREADEVENTS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0815, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETVERSION = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0816, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETCR4 = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0817, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_OPENTHREAD = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0818, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_MAKEWRITABLE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0819, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_STOPDEBUGGING = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x081B, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ALLOCATEMEM = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x081F, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_CREATEAPC = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0820, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETPETHREAD = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0821, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_SUSPENDTHREAD = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0822, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_RESUMETHREAD = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0823, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_SUSPENDPROCESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0824, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_RESUMEPROCESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0825, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ALLOCATEMEM_NONPAGED = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0826, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETPROCADDRESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0827, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETSDTADDRESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0829, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETGDT = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x082A, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_SETCR4 = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x082B, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_VMXCONFIG = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x082D, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETCR0 = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x082E, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_USERDEFINEDINTERRUPTHOOK = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x082F, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_SETGLOBALDEBUGSTATE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0830, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_CONTINUEDEBUGEVENT = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0831, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_WAITFORDEBUGEVENT = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0832, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETDEBUGGERSTATE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0833, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_SETDEBUGGERSTATE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0834, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GD_SETBREAKPOINT = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0835, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_TOUCHDEBUGREGISTER = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0836, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_LAUNCHDBVM = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x083A, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_UNHOOKALLINTERRUPTS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x083B, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_EXECUTE_CODE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x083C, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETPROCESSNAMEADDRESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x083D, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_SETKERNELSTEPABILITY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x083E, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_READMSR = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x083F, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_WRITEMSR = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0840, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_SETSTORELBR = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0841, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0842, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP_DISABLE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0843, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP_WAITFORDATA = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0844, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP_CONTINUE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0845, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP_FLUSH = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0846, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETMEMORYRANGES = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0847, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_STARTACCESMONITOR = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0848, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ENUMACCESSEDMEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0849, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GETACCESSEDMEMORYLIST = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x084A, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_WRITESIGNOREWP = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x084B, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_FREE_NONPAGED = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x084C, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_MAP_MEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x084D, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_UNMAP_MEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x084E, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2 = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x084F, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_DISABLEULTIMAP2 = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0850, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_WAITFORDATA = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0851, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_CONTINUE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0852, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_FLUSH = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0853, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_PAUSE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0854, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_RESUME = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0855, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_LOCKFILE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0856, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_RELEASEFILE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0857, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP_PAUSE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0858, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP_RESUME = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0859, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_GETTRACESIZE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x085A, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ULTIMAP2_RESETTRACESIZE = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x085B, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ENABLE_DRM = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x085C, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_GET_PEB = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x085D, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_QUERYINFORMATIONPROCESS = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x085E, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_LOCK_MEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0860, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_UNLOCK_MEMORY = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0861, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_ALLOCATE_MEMORY_FOR_DBVM = CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0862, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_CE_CREATEREMOTETHREAD = CTL_CODE(IOCTL_UNKNOWN_BASE, 0xF000, METHOD_BUFFERED, FILE_RW_ACCESS);
    public static readonly uint IOCTL_BLACKBONE_INJECT_DLL = CTL_CODE(FILE_DEVICE_BLACKBONE, 0x80B, METHOD_BUFFERED, FILE_RW_ACCESS);
}